# See https://github.com/actions/upload-release-asset

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'go*'

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: golang/go
          ref: ${{ github.ref }}
          path: 'go'
      - name: Build project
        run: |
          cd go/src
          GOOS=plan9 GOARCH=amd64 ./bootstrap.bash
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: go-plan9-amd64-bootstrap.tbz
          asset_name: go-plan9-amd64-bootstrap.tbz
          asset_content_type: application/x-bzip2
